from enum import Enum


class StatoPrenotazione(Enum):
    RICHIESTA = "RICHIESTA"
    CONFERMATA = "CONFERMATA"
    DISDETTA = "DISDETTA"
    IN_CORSO = "IN_CORSO"
    CONCLUSA = "CONCLUSA"


class StatoTavolo(Enum):
    DISPONIBILE = "DISPONIBILE"
    PRENOTATO = "PRENOTATO"
    OCCUPATO = "OCCUPATO"
    IN_PULIZIA = "IN_PULIZIA"
    NON_DISPONIBILE = "NON_DISPONIBILE"


class StatoBuono(Enum):
    ATTIVO = "ATTIVO"
    RISCATTATO = "RISCATTATO"
    SCADUTO = "SCADUTO"


class LivelloAccesso(Enum):
    VISUALIZZAZIONE = "VISUALIZZAZIONE"
    GESTIONE_PRENOTAZIONI = "GESTIONE_PRENOTAZIONI"
    GESTIONE_DIPENDENTI = "GESTIONE_DIPENDENTI"
    ACCESSO_COMPLETO = "ACCESSO_COMPLETO"
